set(_CATKIN_CURRENT_PACKAGE "spyndra")
set(spyndra_VERSION "0.0.0")
set(spyndra_MAINTAINER "danny <ih2320@columbia.edu>")
set(spyndra_PACKAGE_FORMAT "1")
set(spyndra_BUILD_DEPENDS "message_generation" "std_msgs" "roscpp" "rospy")
set(spyndra_BUILD_EXPORT_DEPENDS "message_runtime" "std_msgs" "roscpp" "rospy")
set(spyndra_BUILDTOOL_DEPENDS "catkin")
set(spyndra_BUILDTOOL_EXPORT_DEPENDS )
set(spyndra_EXEC_DEPENDS "message_runtime" "std_msgs" "roscpp" "rospy")
set(spyndra_RUN_DEPENDS "message_runtime" "std_msgs" "roscpp" "rospy")
set(spyndra_TEST_DEPENDS )
set(spyndra_DOC_DEPENDS )
set(spyndra_DEPRECATED "")