set(spyndra_SETUP_PY_VERSION "0.0.0")
set(spyndra_SETUP_PY_SCRIPTS "")
set(spyndra_SETUP_PY_PACKAGES "spyndra")
set(spyndra_SETUP_PY_PACKAGE_DIRS "include/spyndra")
set(spyndra_SETUP_PY_MODULES "")
set(spyndra_SETUP_PY_MODULE_DIRS "")