# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from spyndra/BeaconPos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BeaconPos(genpy.Message):
  _md5sum = "c67a5a42d752c8877f71d8ea372e1063"
  _type = "spyndra/BeaconPos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 timestamp_ms
uint8 address
float64 x_m
float64 y_m
float64 z_m"""
  __slots__ = ['timestamp_ms','address','x_m','y_m','z_m']
  _slot_types = ['int64','uint8','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp_ms,address,x_m,y_m,z_m

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BeaconPos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.timestamp_ms is None:
        self.timestamp_ms = 0
      if self.address is None:
        self.address = 0
      if self.x_m is None:
        self.x_m = 0.
      if self.y_m is None:
        self.y_m = 0.
      if self.z_m is None:
        self.z_m = 0.
    else:
      self.timestamp_ms = 0
      self.address = 0
      self.x_m = 0.
      self.y_m = 0.
      self.z_m = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_qB3d.pack(_x.timestamp_ms, _x.address, _x.x_m, _x.y_m, _x.z_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.timestamp_ms, _x.address, _x.x_m, _x.y_m, _x.z_m,) = _struct_qB3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_qB3d.pack(_x.timestamp_ms, _x.address, _x.x_m, _x.y_m, _x.z_m))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 33
      (_x.timestamp_ms, _x.address, _x.x_m, _x.y_m, _x.z_m,) = _struct_qB3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_qB3d = struct.Struct("<qB3d")
