// Generated by gencpp from file spyndra/BeaconPos.msg
// DO NOT EDIT!


#ifndef SPYNDRA_MESSAGE_BEACONPOS_H
#define SPYNDRA_MESSAGE_BEACONPOS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spyndra
{
template <class ContainerAllocator>
struct BeaconPos_
{
  typedef BeaconPos_<ContainerAllocator> Type;

  BeaconPos_()
    : timestamp_ms(0)
    , address(0)
    , x_m(0.0)
    , y_m(0.0)
    , z_m(0.0)  {
    }
  BeaconPos_(const ContainerAllocator& _alloc)
    : timestamp_ms(0)
    , address(0)
    , x_m(0.0)
    , y_m(0.0)
    , z_m(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _timestamp_ms_type;
  _timestamp_ms_type timestamp_ms;

   typedef uint8_t _address_type;
  _address_type address;

   typedef double _x_m_type;
  _x_m_type x_m;

   typedef double _y_m_type;
  _y_m_type y_m;

   typedef double _z_m_type;
  _z_m_type z_m;




  typedef boost::shared_ptr< ::spyndra::BeaconPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spyndra::BeaconPos_<ContainerAllocator> const> ConstPtr;

}; // struct BeaconPos_

typedef ::spyndra::BeaconPos_<std::allocator<void> > BeaconPos;

typedef boost::shared_ptr< ::spyndra::BeaconPos > BeaconPosPtr;
typedef boost::shared_ptr< ::spyndra::BeaconPos const> BeaconPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spyndra::BeaconPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spyndra::BeaconPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spyndra

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'spyndra': ['/home/pi/Desktop/Spyndra/spyndra/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spyndra::BeaconPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spyndra::BeaconPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spyndra::BeaconPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spyndra::BeaconPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spyndra::BeaconPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spyndra::BeaconPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spyndra::BeaconPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c67a5a42d752c8877f71d8ea372e1063";
  }

  static const char* value(const ::spyndra::BeaconPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc67a5a42d752c887ULL;
  static const uint64_t static_value2 = 0x7f71d8ea372e1063ULL;
};

template<class ContainerAllocator>
struct DataType< ::spyndra::BeaconPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spyndra/BeaconPos";
  }

  static const char* value(const ::spyndra::BeaconPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spyndra::BeaconPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 timestamp_ms\n\
uint8 address\n\
float64 x_m\n\
float64 y_m\n\
float64 z_m\n\
";
  }

  static const char* value(const ::spyndra::BeaconPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spyndra::BeaconPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp_ms);
      stream.next(m.address);
      stream.next(m.x_m);
      stream.next(m.y_m);
      stream.next(m.z_m);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BeaconPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spyndra::BeaconPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spyndra::BeaconPos_<ContainerAllocator>& v)
  {
    s << indent << "timestamp_ms: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timestamp_ms);
    s << indent << "address: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.address);
    s << indent << "x_m: ";
    Printer<double>::stream(s, indent + "  ", v.x_m);
    s << indent << "y_m: ";
    Printer<double>::stream(s, indent + "  ", v.y_m);
    s << indent << "z_m: ";
    Printer<double>::stream(s, indent + "  ", v.z_m);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPYNDRA_MESSAGE_BEACONPOS_H
