// Generated by gencpp from file spyndra/MotorSignal.msg
// DO NOT EDIT!


#ifndef SPYNDRA_MESSAGE_MOTORSIGNAL_H
#define SPYNDRA_MESSAGE_MOTORSIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spyndra
{
template <class ContainerAllocator>
struct MotorSignal_
{
  typedef MotorSignal_<ContainerAllocator> Type;

  MotorSignal_()
    : speed(0)
    , motor_id(0)
    , signal(0)
    , load(0)
    , action_error(0)  {
    }
  MotorSignal_(const ContainerAllocator& _alloc)
    : speed(0)
    , motor_id(0)
    , signal(0)
    , load(0)
    , action_error(0)  {
  (void)_alloc;
    }



   typedef int32_t _speed_type;
  _speed_type speed;

   typedef int32_t _motor_id_type;
  _motor_id_type motor_id;

   typedef int32_t _signal_type;
  _signal_type signal;

   typedef int32_t _load_type;
  _load_type load;

   typedef int32_t _action_error_type;
  _action_error_type action_error;




  typedef boost::shared_ptr< ::spyndra::MotorSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spyndra::MotorSignal_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSignal_

typedef ::spyndra::MotorSignal_<std::allocator<void> > MotorSignal;

typedef boost::shared_ptr< ::spyndra::MotorSignal > MotorSignalPtr;
typedef boost::shared_ptr< ::spyndra::MotorSignal const> MotorSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spyndra::MotorSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spyndra::MotorSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spyndra

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'spyndra': ['/home/pi/Desktop/Spyndra/spyndra/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spyndra::MotorSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spyndra::MotorSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spyndra::MotorSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spyndra::MotorSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spyndra::MotorSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spyndra::MotorSignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spyndra::MotorSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baf7bfab6e1a220674cb24b5f4878d91";
  }

  static const char* value(const ::spyndra::MotorSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbaf7bfab6e1a2206ULL;
  static const uint64_t static_value2 = 0x74cb24b5f4878d91ULL;
};

template<class ContainerAllocator>
struct DataType< ::spyndra::MotorSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spyndra/MotorSignal";
  }

  static const char* value(const ::spyndra::MotorSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spyndra::MotorSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 speed\n\
int32 motor_id\n\
int32 signal\n\
int32 load\n\
int32 action_error\n\
";
  }

  static const char* value(const ::spyndra::MotorSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spyndra::MotorSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.motor_id);
      stream.next(m.signal);
      stream.next(m.load);
      stream.next(m.action_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spyndra::MotorSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spyndra::MotorSignal_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
    s << indent << "motor_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.motor_id);
    s << indent << "signal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.signal);
    s << indent << "load: ";
    Printer<int32_t>::stream(s, indent + "  ", v.load);
    s << indent << "action_error: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPYNDRA_MESSAGE_MOTORSIGNAL_H
